config/routes.rb
Sweetapp::Application.routes.draw do
  

  resources :ref_sets

  
  	match "/statistic/:set_code" => "out_standing_work_index#statistic"
  	match "/paststats/:set_code/:month/:year" => "out_standing_work_index#paststats"
  	match "/paststats/" => "out_standing_work_index#paststats"
  	match "/tatbyday/:set_code/:month/:year" => "out_standing_work_index#tatbyday"
  	match "/tatbyday/" => "out_standing_work_index#tatbyday"
  	match "/outstandingsets" => "out_standing_work_index#outstandingsets"
  	match "/statistics" => "out_standing_work_index#statistics"
  	match "/historical/:set_code/:month/:year" => "out_standing_work_index#historical"
  	match "/historical/" => "out_standing_work_index#historical"
  	match "/amu/" => "amu#outstanding"
  	match "/patmeans/:start_date/:end_date/:set_code/" => "stats#patient_means"
  	match "/tats/:week_no" => "tats#tatsperformance"
  	match "/tats/" => "tats#tatsperformance"
  	
     resources :out_standing_work_index do
      member do
         get 'short'
         post 'toggle'
       end
  
       collection do
         get 'gen_xml'
         get 'statistics'
         {:statistic => :get}
       end
     end

  
   
   root :to => "home#index"
   

end

app/models/ref_set.rb
class RefSet < CachedModel
  set_table_name :Ref_Set

end

app/controllers/ref_sets_controller.rb
class RefSetsController < ApplicationController
  # GET /ref_sets
  # GET /ref_sets.xml
  def index
    @ref_sets = RefSet.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ref_sets }
    end
  end

  # GET /ref_sets/1
  # GET /ref_sets/1.xml
  def show
    @ref_set = RefSet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ref_set }
    end
  end

  # GET /ref_sets/new
  # GET /ref_sets/new.xml
  def new
    @ref_set = RefSet.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ref_set }
    end
  end

  # GET /ref_sets/1/edit
  def edit
    @ref_set = RefSet.find(params[:id])
  end

  # POST /ref_sets
  # POST /ref_sets.xml
  def create
    @ref_set = RefSet.new(params[:ref_set])

    respond_to do |format|
      if @ref_set.save
        format.html { redirect_to(@ref_set, :notice => 'Ref set was successfully created.') }
        format.xml  { render :xml => @ref_set, :status => :created, :location => @ref_set }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ref_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ref_sets/1
  # PUT /ref_sets/1.xml
  def update
    @ref_set = RefSet.find(params[:id])

    respond_to do |format|
      if @ref_set.update_attributes(params[:ref_set])
        format.html { redirect_to(@ref_set, :notice => 'Ref set was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ref_set.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ref_sets/1
  # DELETE /ref_sets/1.xml
  def destroy
    @ref_set = RefSet.find(params[:id])
    @ref_set.destroy

    respond_to do |format|
      format.html { redirect_to(ref_sets_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/ref_sets_helper.rb
module RefSetsHelper
end

app/views/ref_sets/_form.html.erb
<%= form_for(@ref_set) do |f| %>
  <% if @ref_set.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ref_set.errors.count, "error") %> prohibited this ref_set from being saved:</h2>

      <ul>
      <% @ref_set.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ref_sets/edit.html.erb
<h1>Editing ref_set</h1>

<%= render 'form' %>

<%= link_to 'Show', @ref_set %> |
<%= link_to 'Back', ref_sets_path %>

app/views/ref_sets/index.html.erb
<h1>Listing ref_sets</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ref_sets.each do |ref_set| %>
  <tr>
    <td><%= link_to 'Show', ref_set %></td>
    <td><%= link_to 'Edit', edit_ref_set_path(ref_set) %></td>
    <td><%= link_to 'Destroy', ref_set, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ref set', new_ref_set_path %>

app/views/ref_sets/new.html.erb
<h1>New ref_set</h1>

<%= render 'form' %>

<%= link_to 'Back', ref_sets_path %>

app/views/ref_sets/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_ref_set_path(@ref_set) %> |
<%= link_to 'Back', ref_sets_path %>